name: certeef

env:
  CARGO_TERM_COLOR: always

inputs:
  github_token:
    required: true
  cargo_registry_token:
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - name: Build
    run: cargo build --verbose
    shell: bash

  - name: Run tests
    run: |
      cd certeef
      pwd 
      cargo test --verbose
    shell: bash

  - name : Crate.io login
    run: |
      cd certeef
      pwd
      cargo login ${{ inputs.cargo_registry_token }}
    shell: bash
    env:
      # This can help you publish to crates.io
      CARGO_REGISTRY_TOKEN: ${{ inputs.cargo_registry_token }}

  - name: Run publish-action
    id: publish-action
    run: |
      cargo publish --token ${{ inputs.cargo_registry_token }} -v --allow-dirty --manifest-path certeef/Cargo.toml
    shell: bash
    env:
      # This can help you tagging the github repository
      GITHUB_TOKEN: ${{ inputs.github_token }}
      # This can help you publish to crates.io
      CARGO_REGISTRY_TOKEN: ${{ inputs.cargo_registry_token }}