name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
      working-directory: certeef

    - name: Run tests
      run: cargo test --verbose
      working-directory: certeef

    # install publish-action by cargo in github action
    - name: Install publish-action
      if: steps.cache-publish-action.outputs.cache-hit != 'true'
      run: cargo install publish-action --version=0.2.0
      
    - name: Run publish-action
      id: publish-action
      run: publish-action
      working-directory: certeef
      env:
        # This can help you tagging the github repository
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # This can help you publish to crates.io
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      

