name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - run: cargo build --verbose
    - run: cargo test --verbose

    - name: Build/Test and Publish the certeef lib to crates.io
      uses: ./.github/actions/certeef
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        cargo_registry_token: ${{ secrets.CARGO_REGISTRY_TOKEN }}